spring:
 application:
  name: army
 servlet:
  multipart:
   max-file-size: 1024MB
   max-request-size: 1024MB

 # 配置thymeleaf视图
 resources:
  static-locations: classpath:/static/
 thymeleaf:
  # 开发时关闭缓存,不然没法看到实时页面
  enabled: true 
  prefix: classpath:/templates/ 
  suffix: .html
  encoding: UTF-8
  # 用非严格的 HTML
  mode: LEGACYHTML5 
  servlet:
     content-type: text/html
  cache: false
 jpa:
  open-in-view: false
  show-sql: true
  hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
    format_sql: true
    ddl-auto: update
 datasource:
  username: root
  password: guido1222
  url: jdbc:mysql://localhost:3306/guido?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
  #schema: classpath:schema.sql
  #data: classpath:data.sql
  driver-class-name: com.mysql.jdbc.Driver
  # 配置druid数据连接池
  type: com.alibaba.druid.pool.DruidDataSource
  # 监控统计拦截的filters
  filters: 
   commons-log.connection-logger-name: stat,wall,log4j
  # 连接池的初始大小、最小、最大
  initialSize: 5
  minIdle: 5
  maxActive: 20
  # 获取连接的超时时间
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  # 一个连接在池中最小生存的时间
  minEvictableIdleTimeMillis: 300000
  #validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: false
  maxPoolPreparedStatementPerConnectionSize: 20
  connectionProperties:
   druid:
    stat:
     mergeSql: true
     slowSqlMillis: 5000

server:
 port: 8081
eureka:
 client:
  registerWithEureka: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/

logging:
 level:
  root: info 
  spring:
   security: debug
  org:
   hibernate:
    type:
     descriptor:
      sql:
       BasicBinder: debug
       #BasicBinder: trace




